DROP TABLE IF EXISTS moons;
DROP TABLE IF EXISTS planets;
DROP TABLE IF EXISTS star_systems;
DROP TABLE IF EXISTS ftlw_overrides;
DROP TABLE IF EXISTS ftlw_chunks;
DROP TABLE IF EXISTS stars;
DROP TABLE IF EXISTS nebulae;
DROP TABLE IF EXISTS galaxies;
