package economy2

import (
	"context"
	"fmt"
	"math"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// RouteStatus is the lifecycle state of a transport route.
type RouteStatus string

const (
	RouteStatusActive    RouteStatus = "active"
	RouteStatusSuspended RouteStatus = "suspended"
)

// Warning is generated by AllocateCapacity when orders are throttled or delayed.
type Warning struct {
	Type    string
	OrderID uuid.UUID
	RouteID uuid.UUID
	Message string
}

// Route is the in-memory representation of an econ2_routes row.
type Route struct {
	ID                 uuid.UUID   `json:"id"`
	PlayerID           uuid.UUID   `json:"player_id"`
	FromNodeID         uuid.UUID   `json:"from_node_id"`
	ToNodeID           uuid.UUID   `json:"to_node_id"`
	CapacityPerTick    float64     `json:"capacity_per_tick"`
	MinContinuousShare float64     `json:"min_continuous_share"`
	Status             RouteStatus `json:"status"`
}

// AllocateCapacity distributes route capacity between batch (max 80%) and continuous (min 20%) orders.
// Unused batch capacity overflows to the continuous pool.
// Returns warnings for throttled or delayed orders.
func (r *Route) AllocateCapacity(batches, continuous []*ProductionOrder) []Warning {
	var warnings []Warning

	share := r.MinContinuousShare
	if share <= 0 {
		share = 0.20
	}

	batchCap := r.CapacityPerTick * (1 - share)
	continuousCap := r.CapacityPerTick * share

	remaining := batchCap
	for _, order := range batches {
		needed := order.TransportNeedPerTick()
		take := math.Min(needed, remaining)
		remaining -= take
		if take < needed {
			warnings = append(warnings, Warning{
				Type:    "batch_delayed",
				OrderID: order.ID,
				RouteID: r.ID,
				Message: fmt.Sprintf("Route %s überlastet – Fertigstellung verzögert", r.ID),
			})
		}
	}

	// Unused batch slot flows to continuous pool.
	continuousCap += remaining

	totalNeed := 0.0
	for _, o := range continuous {
		totalNeed += o.TransportNeedPerTick()
	}

	for _, order := range continuous {
		if totalNeed == 0 {
			break
		}
		alloc := (order.TransportNeedPerTick() / totalNeed) * continuousCap
		if alloc < order.TransportNeedPerTick() {
			pct := 0.0
			if order.TransportNeedPerTick() > 0 {
				pct = (alloc / order.TransportNeedPerTick()) * 100
			}
			warnings = append(warnings, Warning{
				Type:    "continuous_throttled",
				OrderID: order.ID,
				RouteID: r.ID,
				Message: fmt.Sprintf("%.0f%% Kapazität – Produktion gedrosselt", pct),
			})
		}
	}

	return warnings
}

// CreateRoute inserts a new route and sets r.ID.
func CreateRoute(ctx context.Context, db *pgxpool.Pool, r *Route) error {
	return db.QueryRow(ctx, `
		INSERT INTO econ2_routes (player_id, from_node_id, to_node_id, capacity_per_tick, min_continuous_share, status)
		VALUES ($1,$2,$3,$4,$5,$6)
		RETURNING id
	`, r.PlayerID, r.FromNodeID, r.ToNodeID, r.CapacityPerTick, r.MinContinuousShare, string(r.Status)).Scan(&r.ID)
}

// ListRoutesByPlayer returns all routes for a player.
func ListRoutesByPlayer(ctx context.Context, db *pgxpool.Pool, playerID uuid.UUID) ([]Route, error) {
	rows, err := db.Query(ctx, `
		SELECT id, player_id, from_node_id, to_node_id, capacity_per_tick, min_continuous_share, status
		FROM econ2_routes WHERE player_id=$1
	`, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []Route
	for rows.Next() {
		var (
			ro     Route
			status string
		)
		if err := rows.Scan(
			&ro.ID, &ro.PlayerID, &ro.FromNodeID, &ro.ToNodeID,
			&ro.CapacityPerTick, &ro.MinContinuousShare, &status,
		); err != nil {
			return nil, err
		}
		ro.Status = RouteStatus(status)
		result = append(result, ro)
	}
	return result, rows.Err()
}
